.vscode/settings.json, src/main/java/com/saeromteo/app/controller/envdata/EnvDataController.java, src/main/java/com/saeromteo/app/dao/envdata/EnvDataDao.java, src/main/java/com/saeromteo/app/dto/envdata/EnvironmentDataDto.java, src/main/java/com/saeromteo/app/service/envdata/EnvDataService.java, src/main/java/com/saeromteo/app/vo/notice/NoticeDAOInterface.java, src/main/java/com/saeromteo/app/vo/notice/NoticeDAOMybatis.java, src/main/java/com/saeromteo/app/vo/notice/NoticeDTO.java, src/main/resources/mybatis/SqlMapConfig.xml, src/main/resources/mybatis/mappers/envDataDao.xml, src/main/resources/mybatis/mappers/noticeMapper.xml, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/web.xml
- DTO 작성
- DAO, mybatis 작성
- mapper 작성
=> Feature notice crud

.vscode/settings.json, pom.xml, src/main/java/com/saeromteo/app/config/S3Config.java, src/main/java/com/saeromteo/app/controller/envdata/EnvDataController.java, src/main/java/com/saeromteo/app/controller/order/paymentsController.java, src/main/java/com/saeromteo/app/dao/envdata/EnvDataDao.java, src/main/java/com/saeromteo/app/dto/envdata/EnvironmentDataDto.java, src/main/java/com/saeromteo/app/service/envdata/EnvDataService.java, src/main/java/com/saeromteo/app/service/order/awstest.java, src/main/java/com/saeromteo/app/vo/notice/NoticeDAOInterface.java, src/main/java/com/saeromteo/app/vo/notice/NoticeDAOMybatis.java, src/main/java/com/saeromteo/app/vo/notice/NoticeDTO.java, src/main/resources/mybatis/SqlMapConfig.xml, src/main/resources/mybatis/mappers/envDataDao.xml, src/main/resources/mybatis/mappers/noticeMapper.xml, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/payments/portoneTest.jsp, src/main/webapp/WEB-INF/web.xml
- aws s3 연동 
- 카카오페이, 이니시스 카드 결제 테스트
pom.xml , root-context.xml 파일 변동,, 화이탱 !!
=> Feature order implementation

src/main/java/com/saeromteo/app/util/DateUtil.java
=> [Bugfix] restore dateUtil

src/main/java/com/saeromteo/app/controller/notice/NoticeController.java, src/main/java/com/saeromteo/app/controller/question/QuestionController.java, src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java, src/main/java/com/saeromteo/app/dao/notice/NoticeDAOInterface.java, src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java, src/main/java/com/saeromteo/app/dao/question/QuestionDAOInterface.java, src/main/java/com/saeromteo/app/dao/review/ReviewDao.java, src/main/java/com/saeromteo/app/dao/review/ReviewInterface.java, src/main/java/com/saeromteo/app/dto/notice/NoticeDTO.java, src/main/java/com/saeromteo/app/dto/notice/NoticeEntity.java, src/main/java/com/saeromteo/app/dto/question/QuestionDTO.java, src/main/java/com/saeromteo/app/dto/review/ReviewDto.java, src/main/java/com/saeromteo/app/dto/review/ReviewEntity.java, src/main/java/com/saeromteo/app/service/notice/NoticeService.java, src/main/java/com/saeromteo/app/service/question/QuestionService.java, src/main/resources/mybatis/SqlMapConfig.xml, src/main/resources/mybatis/mappers/noticeMapper.xml, src/main/resources/mybatis/mappers/questionMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml
=> 🌟(#33 ) 상품후기 crud

src/main/java/com/saeromteo/app/dao/EnvDataDao.java, src/main/java/com/saeromteo/app/dao/NewsDao.java, src/main/java/com/saeromteo/app/dao/QuizDao.java, src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java, src/main/java/com/saeromteo/app/dao/order/OrderDao.java, src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java, src/main/resources/mybatis/EnvDataSqlMapConfig.xml, src/main/resources/mybatis/NewsSqlMapConfig.xml, src/main/resources/mybatis/NoticeSqlMapConfig.xml, src/main/resources/mybatis/QuizSqlMapConfig.xml, src/main/resources/mybatis/mappers/noticeDao.xml, src/main/resources/mybatis/mappers/orderMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml
=> (#28) sqlconfig파일 분리 완료

src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java, src/main/java/com/saeromteo/app/dao/product/ProductDAO.java, src/main/java/com/saeromteo/app/dao/review/ReviewDao.java, src/main/resources/mybatis/ProductSqlMapConfig.xml, src/main/webapp/WEB-INF/spring/root-context.xml
=> 🌟(#28) sqlconfig파일 분리 완료

src/main/java/com/saeromteo/app/controller/question/QuestionController.java, src/main/java/com/saeromteo/app/dao/EnvDataDao.java, src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java, src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java, src/main/java/com/saeromteo/app/dto/question/QuestionDTO.java, src/main/resources/mybatis/QuestionSqlMapConfig.xml, src/main/resources/mybatis/mappers/noticeMapper.xml, src/main/resources/mybatis/mappers/questionMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml
=> 🌟(#33 ) DTO변수명 수정, vo생성

pom.xml, src/main/java/com/saeromteo/app/config/SwaggerConfig.java, src/main/java/com/saeromteo/app/controller/collection/CollectionController.java, src/main/java/com/saeromteo/app/model/collection/CollectionDto.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
=> 🌟(#42) Swagger 적용

src/main/java/com/saeromteo/app/controller/order/OrderController.java, src/main/java/com/saeromteo/app/controller/order/PaymentsController.java, src/main/java/com/saeromteo/app/dao/order/OrderDao.java, src/main/java/com/saeromteo/app/dao/order/OrderDaoInterface.java, src/main/java/com/saeromteo/app/dao/order/PaymentDao.java, src/main/java/com/saeromteo/app/dao/order/PaymentDaoInterface.java, src/main/java/com/saeromteo/app/model/order/RecipientInfoDto.java, src/main/java/com/saeromteo/app/service/order/OrderService.java, src/main/java/com/saeromteo/app/service/order/PaymentService.java, src/main/resources/mybatis/SqlMapConfig.xml, src/main/resources/mybatis/mappers/orderMapper.xml, src/main/webapp/WEB-INF/views/payments/portoneTest.jsp
- 배송지 정보 전달 
- 주문 정보 전달
- 주문 상태 업데이트
=> 🌟(#28) 주문 정보 전달 

src/main/java/com/saeromteo/app/controller/review/ReviewController.java, src/main/java/com/saeromteo/app/dao/envdata/EnvDataDao.java, src/main/java/com/saeromteo/app/dao/review/ReviewDao.java, src/main/java/com/saeromteo/app/service/review/ReviewService.java, src/main/resources/mybatis/ReviewSqlMapConfig.xml, src/main/resources/mybatis/mappers/reviewMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml
- controller 생성
- mapper 생성
- service 생성
=> 🌟(#33) 상품후기 crud

src/main/java/com/saeromteo/app/dto/product/ProductDTO.java, src/main/resources/mybatis/mappers/productMapper.xml
=> 🌟(#8 ) 상품 crud 

.containerignore, Containerfile, pom.xml, src/main/java/com/saeromteo/app/config/SwaggerConfig.java, src/main/java/com/saeromteo/app/controller/order/PaymentsController.java, src/main/java/com/saeromteo/app/controller/product/ProductCategoryController.java, src/main/java/com/saeromteo/app/controller/product/ProductController.java, src/main/java/com/saeromteo/app/controller/review/ReviewController.java, src/main/java/com/saeromteo/app/dao/envdata/EnvDataDao.java, src/main/java/com/saeromteo/app/dao/product/ProductCategoryDAO.java, src/main/java/com/saeromteo/app/dao/review/ReviewDao.java, src/main/java/com/saeromteo/app/dto/product/ProductCategoryDTO.java, src/main/java/com/saeromteo/app/dto/product/ProductDTO.java, src/main/java/com/saeromteo/app/service/order/awstest.java, src/main/java/com/saeromteo/app/service/product/ProductCategoryService.java, src/main/java/com/saeromteo/app/service/review/ReviewService.java, src/main/resources/mybatis/ProductCategorySqlMapConfig.xml, src/main/resources/mybatis/ReviewSqlMapConfig.xml, src/main/resources/mybatis/mappers/ProductCategoryMapper.xml, src/main/resources/mybatis/mappers/productMapper.xml, src/main/resources/mybatis/mappers/reviewMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml
- dto, dao, service, controller 생성
- mapper 생성
=> 🌟(#34) 상품 카테고리 crud 

src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java, src/main/java/com/saeromteo/app/dao/wishlist/WishlistDAO.java, src/main/java/com/saeromteo/app/dto/wishlist/WishlistDTO.java, src/main/java/com/saeromteo/app/service/wishlist/WishlistService.java, src/main/resources/mybatis/WishlistSqlMapConfig.xml, src/main/resources/mybatis/mappers/WishlistMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml
- dto,dao, service, controller 생성
- mapper 생성
=> 🌟(#50) 위시리스트 crud

src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java, src/main/java/com/saeromteo/app/controller/collection/CollectionController.java, src/main/java/com/saeromteo/app/model/collection/CollectionDto.java, src/main/java/com/saeromteo/app/service/collection/CollectionService.java, src/main/resources/static/js/address_input.js, src/main/resources/static/js/image_upload.js, src/main/webapp/WEB-INF/html/collection.html, src/main/webapp/WEB-INF/views/collection/collection.html, src/main/webapp/WEB-INF/views/collection/registration.jsp, src/main/webapp/WEB-INF/views/collection/request.jsp, src/main/webapp/WEB-INF/views/collection/test.html
- 주소 api 연동
- 수거 신청 form 제작
- 수거 등록 form 제작
- DB에 정보 입력
=> 🌟(#66) 수거 신청, 등록 기능 구현

src/main/java/com/saeromteo/app/controller/product/ProductController.java, src/main/java/com/saeromteo/app/controller/review/ReviewController.java, src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java, src/main/java/com/saeromteo/app/dao/product/ProductDAO.java, src/main/java/com/saeromteo/app/dao/review/ReviewDao.java, src/main/java/com/saeromteo/app/dao/review/ReviewInterface.java, src/main/java/com/saeromteo/app/dao/wishlist/WishlistDAO.java, src/main/java/com/saeromteo/app/dto/product/ProductCategoryDTO.java, src/main/java/com/saeromteo/app/dto/product/ProductDTO.java, src/main/java/com/saeromteo/app/dto/review/ReviewDto.java, src/main/java/com/saeromteo/app/service/product/ProductService.java, src/main/java/com/saeromteo/app/service/review/ReviewService.java, src/main/java/com/saeromteo/app/service/wishlist/WishlistService.java, src/main/resources/mybatis/ReviewSqlMapConfig.xml, src/main/resources/mybatis/mappers/basketMapper.xml, src/main/resources/mybatis/mappers/discountMapper.xml, src/main/resources/mybatis/mappers/productCategoryMapper.xml, src/main/resources/mybatis/mappers/productMapper.xml, src/main/resources/mybatis/mappers/reviewMapper.xml, src/main/resources/mybatis/mappers/wishlistMapper.xml
- 상품 카테고리 db 재설계
- 상품 카테고리 dto, dao, controller, service, mapper 수정
- 상품, 위시리스트, 후기 페이징 처리 
- 상품 할인율 계산 mapper 수정
=> 🌟(#64 ) 상품, 상품카테고리, 위시리스트, 후기 수정

src/main/java/com/saeromteo/app/controller/review/ReviewController.java, src/main/java/com/saeromteo/app/dao/review/ReviewDao.java, src/main/java/com/saeromteo/app/dao/review/ReviewInterface.java, src/main/java/com/saeromteo/app/dto/review/ReviewDto.java, src/main/java/com/saeromteo/app/service/review/ReviewService.java, src/main/resources/mybatis/ReviewSqlMapConfig.xml
=> 🌟(#72 ) notice variable

src/main/java/com/saeromteo/app/controller/editor/EditorController.java, src/main/resources/static/css/question.css, src/main/webapp/WEB-INF/views/question/question-write.jsp
=> 🌟(#67 ) editor css 적용

src/main/java/com/saeromteo/app/controller/dashboard/DashboardController.java, src/main/java/com/saeromteo/app/controller/news/NewsApiController.java, src/main/java/com/saeromteo/app/controller/news/NewsFrontController.java, src/main/resources/mybatis/mappers/envDataMapper.xml, src/main/resources/static/css/envdata.css, src/main/webapp/WEB-INF/views/admin/createEnvData.jsp, src/main/webapp/WEB-INF/views/dashboard/dashboard.jsp, src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
=> 🌟(#95) 환경 자료 기능 완성하기

src/main/java/com/saeromteo/app/controller/admin/AdminApiController.java, src/main/java/com/saeromteo/app/controller/admin/AdminController.java, src/main/java/com/saeromteo/app/model/collection/CollectionEntity.java, src/main/java/com/saeromteo/app/service/collection/CollectionService.java, src/main/resources/static/css/admin-styles.css, src/main/resources/static/js/admin/datatables-simple-demo.js, src/main/resources/static/js/admin/scripts.js, src/main/webapp/WEB-INF/views/admin/collection-manager.jsp, src/main/webapp/WEB-INF/views/admin/dashboard.jsp, src/main/webapp/WEB-INF/views/admin/nav.jsp, src/main/webapp/WEB-INF/views/admin/side-nav.jsp
=> 🌟(#110) 관리자 페이지 제작

src/main/webapp/WEB-INF/web.xml
=> 🌟(#122 ) mysql listener 오탈자 수정

pom.xml, src/main/java/com/saeromteo/app/config/OAuthConfig.java, src/main/java/com/saeromteo/app/config/SecurityConfig.java, src/main/java/com/saeromteo/app/controller/user/OAuth2Controller.java, src/main/java/com/saeromteo/app/controller/user/UserController.java, src/main/java/com/saeromteo/app/dto/user/UserDTO.java, src/main/java/com/saeromteo/app/service/envdata/EnvDataService.java
=> 🌟(#124 ) Fix UserDTO

src/main/java/com/saeromteo/app/config/AppConfig.java, src/main/java/com/saeromteo/app/config/AsyncConfig.java, src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java, src/main/java/com/saeromteo/app/dao/collection/CollectionDao.java, src/main/java/com/saeromteo/app/model/collection/CollectionEntity.java, src/main/java/com/saeromteo/app/service/collection/CollectionService.java, src/main/java/com/saeromteo/app/util/InspectionUtil.java, src/main/resources/mybatis/mappers/collectionMapper.xml, src/main/resources/static/js/admin/scripts.js, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
=> 🌟(#97) 수거 요청 결과 저장 로직 수정

src/main/java/com/saeromteo/app/controller/admin/AdminController.java, src/main/java/com/saeromteo/app/controller/news/NewsFrontController.java, src/main/java/com/saeromteo/app/dto/envdata/EnvironmentDataDto.java, src/main/java/com/saeromteo/app/dto/quiz/QuizDto.java, src/main/java/com/saeromteo/app/service/envdata/EnvDataService.java, src/main/resources/mybatis/mappers/envDataMapper.xml, src/main/resources/mybatis/mappers/newsMapper.xml, src/main/resources/mybatis/mappers/quizMapper.xml, src/main/webapp/WEB-INF/views/admin/envdata-manager.jsp, src/main/webapp/WEB-INF/views/admin/news-manager.jsp, src/main/webapp/WEB-INF/views/admin/quiz-manager.jsp, src/main/webapp/WEB-INF/views/admin/side-nav.jsp
=> 🌟(#113) 어드민 페이지 완성

src/main/java/com/saeromteo/app/config/AppConfig.java, src/main/java/com/saeromteo/app/config/SecurityConfig.java, src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java, src/main/java/com/saeromteo/app/dao/user/UserDAO.java, src/main/java/com/saeromteo/app/dto/user/UserDTO.java, src/main/java/com/saeromteo/app/dto/user/UserInfoDTO.java, src/main/java/com/saeromteo/app/service/collection/CollectionService.java, src/main/java/com/saeromteo/app/service/user/UserService.java, src/main/resources/mybatis/mappers/userMapper.xml, src/main/webapp/WEB-INF/views/admin/collection-manager.jsp, src/main/webapp/WEB-INF/views/collection/regist-submit.jsp, src/main/webapp/WEB-INF/views/collection/request-submit.jsp
=> 🌟(#110) 수거 신청, 요청 기본값 설정

src/main/java/com/saeromteo/app/controller/basket/BasketController.java, src/main/resources/mybatis/mappers/basketMapper.xml, src/main/resources/mybatis/mappers/productMapper.xml, src/main/webapp/WEB-INF/views/basket/basket.jsp, src/main/webapp/WEB-INF/views/product/product-detail.jsp
=> 🌟(#79 ) 상품, 장바구니 페이지 수정

src/main/java/com/saeromteo/app/controller/admin/AdminApiController.java, src/main/java/com/saeromteo/app/controller/admin/AdminController.java, src/main/java/com/saeromteo/app/controller/notice/NoticeController.java, src/main/java/com/saeromteo/app/controller/question/FileApiController.java, src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java, src/main/java/com/saeromteo/app/dto/notice/NoticeDTO.java, src/main/java/com/saeromteo/app/dto/question/QuestionDTO.java, src/main/java/com/saeromteo/app/service/question/FileService.java, src/main/java/com/saeromteo/app/service/question/QuestionService.java, src/main/java/com/saeromteo/app/util/S3Util.java, src/main/resources/mybatis/mappers/questionMapper.xml, src/main/webapp/WEB-INF/views/admin/notice-manager.jsp, src/main/webapp/WEB-INF/views/admin/question-manager.jsp, src/main/webapp/WEB-INF/views/admin/side-nav.jsp, src/main/webapp/WEB-INF/views/question/question-write.jsp
=> 🌟(#114 ) 관리자페이지 공지사항 crud

src/main/java/com/saeromteo/app/controller/notice/NoticeController.java, src/main/java/com/saeromteo/app/controller/question/QuestionController.java, src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java, src/main/resources/mybatis/mappers/questionMapper.xml, src/main/resources/static/css/faq.css, src/main/resources/static/css/notice.css, src/main/resources/static/css/question.css, src/main/resources/static/js/faq.js, src/main/resources/static/js/question.js, src/main/webapp/WEB-INF/views/admin/notice-manager.jsp, src/main/webapp/WEB-INF/views/admin/question-manager.jsp, src/main/webapp/WEB-INF/views/editor/editor-question-form.jsp, src/main/webapp/WEB-INF/views/notice/notice.jsp, src/main/webapp/WEB-INF/views/question/question-write.jsp, src/main/webapp/WEB-INF/views/question/question.jsp
- 관리자 페이지 공지, 문의사항 CRUD
- 유저페이지 css 수정
=> 🌟(#96) 관리자 페이지, 유저페이지

src/main/java/com/saeromteo/app/controller/product/ProductController.java, src/main/java/com/saeromteo/app/controller/review/ReviewController.java, src/main/java/com/saeromteo/app/controller/review/ReviewFrontController.java, src/main/java/com/saeromteo/app/dao/review/ReviewDao.java, src/main/java/com/saeromteo/app/dao/review/ReviewInterface.java, src/main/java/com/saeromteo/app/dao/review/ReviewSearchDto.java, src/main/java/com/saeromteo/app/service/review/ReviewService.java, src/main/resources/mybatis/mappers/reviewMapper.xml, src/main/resources/static/css/product-detail-review.css, src/main/resources/static/css/review.css, src/main/webapp/WEB-INF/views/product/product-detail-review.jsp, src/main/webapp/WEB-INF/views/product/product-detail.jsp, src/main/webapp/WEB-INF/views/review/review.jsp
- product detail 내 후기 기능
- 내역 반
=> 🌟(#145) 상품 후기 기능

src/main/java/com/saeromteo/app/controller/afterSales/AfterSalesController.java, src/main/java/com/saeromteo/app/controller/orderInquiry/OrderInquiryController.java, src/main/resources/static/css/orderDetailnquriy.css, src/main/resources/static/css/orderInquiry.css, src/main/webapp/WEB-INF/views/orderInquiry/orderDetailnquriy.jsp, src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry.jsp
=> 🌟(#115) 주문 상세 조회 

src/main/java/com/saeromteo/app/controller/admin/AdminController.java, src/main/java/com/saeromteo/app/controller/product/ProductController.java, src/main/java/com/saeromteo/app/controller/review/ReviewController.java, src/main/java/com/saeromteo/app/dao/product/ProductCategoryDAO.java, src/main/java/com/saeromteo/app/model/product/ProductEntity.java, src/main/java/com/saeromteo/app/service/product/ProductCategoryService.java, src/main/resources/mybatis/mappers/productMapper.xml, src/main/resources/static/css/product-detail-review.css, src/main/resources/static/css/product.css, src/main/resources/static/css/wishlist.css, src/main/webapp/WEB-INF/views/admin/product-discount-manager.jsp, src/main/webapp/WEB-INF/views/admin/product-manager.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp, src/main/webapp/WEB-INF/views/product/product-detail.jsp, src/main/webapp/WEB-INF/views/product/product.jsp
- 상품 카테고리별 정렬 기능 구현, 상품/할인 db 수정
- 상품, 상품 상세, 장바구니, 위시리스트, 관리자p 수정
=> 🌟(#138) 상품 카테고리 수정

src/main/java/com/saeromteo/app/controller/afterSales/AfterSalesController.java, src/main/java/com/saeromteo/app/controller/orderInquiry/OrderInquiryController.java, src/main/java/com/saeromteo/app/service/orderInquiry/OrderInquiryService.java, src/main/resources/mybatis/mappers/orderInquiryMapper.xml, src/main/resources/static/css/basket.css, src/main/resources/static/css/orderInquiry.css, src/main/resources/static/css/refund.css, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/orderInquiry/orderDetailnquriy.jsp, src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry.jsp, src/main/webapp/WEB-INF/views/refund/refund.jsp
=> 🌟(#115) 주문 내역 상세 조회 및 환불 페이지 

src/main/webapp/WEB-INF/views/collection/header.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-collection.jsp
=> 🌟(#146) header 충돌 복구

src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java, src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java, src/main/java/com/saeromteo/app/controller/point/PointController.java, src/main/java/com/saeromteo/app/model/point/PointDto.java, src/main/java/com/saeromteo/app/service/collection/CollectionService.java, src/main/java/com/saeromteo/app/service/point/PointService.java, src/main/resources/mybatis/mappers/pointMapper.xml, src/main/webapp/WEB-INF/views/admin/point-manager.jsp, src/main/webapp/WEB-INF/views/collection/regist-complete.jsp, src/main/webapp/WEB-INF/views/collection/request-complete.jsp, src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
=> 🌟(#146) 포인트 관리자 페이지 제작

src/main/webapp/WEB-INF/views/admin/envdata-manager.jsp, src/main/webapp/WEB-INF/views/admin/news-manager.jsp, src/main/webapp/WEB-INF/views/admin/quiz-manager.jsp, src/main/webapp/WEB-INF/views/dashboard/dashboard.jsp, src/main/webapp/WEB-INF/views/dashboard/envdata.jsp, src/main/webapp/WEB-INF/views/dashboard/envdetail.jsp, src/main/webapp/WEB-INF/views/dashboard/news.jsp, src/main/webapp/WEB-INF/views/dashboard/quiz.jsp, src/main/webapp/WEB-INF/views/editor/editor-envdata-form.jsp, src/main/webapp/WEB-INF/views/review/review.jsp
=> 🌟(#163) 에디터 적용 시도 및 경로 설정

src/main/java/com/saeromteo/app/controller/product/ProductController.java, src/main/java/com/saeromteo/app/dao/product/ProductDAO.java, src/main/java/com/saeromteo/app/model/product/ProductEntity.java, src/main/java/com/saeromteo/app/service/product/ProductService.java, src/main/resources/mybatis/mappers/productMapper.xml, src/main/webapp/WEB-INF/views/product/product.jsp
=> 🌟(#138) 상품 카테고리 정렬

.github/workflows/main.yml
=> workflow 수정

src/main/java/com/saeromteo/app/controller/MainController.java, src/main/java/com/saeromteo/app/controller/basket/BasketController.java, src/main/java/com/saeromteo/app/controller/product/ProductController.java, src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java, src/main/java/com/saeromteo/app/dao/product/ProductDAO.java, src/main/java/com/saeromteo/app/service/product/ProductService.java, src/main/resources/mybatis/mappers/basketMapper.xml, src/main/resources/mybatis/mappers/productMapper.xml, src/main/resources/mybatis/mappers/wishlistMapper.xml, src/main/resources/static/css/basket.css, src/main/resources/static/css/main.css, src/main/resources/static/css/product-detail-review.css, src/main/resources/static/css/wishlist.css, src/main/webapp/WEB-INF/views/main.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp, src/main/webapp/WEB-INF/views/product/product-detail.jsp, src/main/webapp/WEB-INF/views/product/product.jsp
- 메인 페이지 상품 부분 추가 (인기순, 할인순)
-  유저 연결
=> 🌟(#180 ) 메인 페이지 수정

src/main/java/com/saeromteo/app/controller/order/OrderController.java, src/main/java/com/saeromteo/app/controller/orderInquiry/OrderInquiryController.java, src/main/java/com/saeromteo/app/service/order/OrderService.java, src/main/resources/mybatis/mappers/orderInquiryMapper.xml, src/main/resources/mybatis/mappers/orderMapper.xml, src/main/resources/static/css/order.css, src/main/resources/static/css/orderDetailnquriy.css, src/main/resources/static/css/refund.css, src/main/webapp/WEB-INF/views/collection/regist-submit.jsp, src/main/webapp/WEB-INF/views/order/orderpage.jsp, src/main/webapp/WEB-INF/views/orderInquiry/orderDetailnquriy.jsp, src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry.jsp, src/main/webapp/WEB-INF/views/refund/refund.jsp
=> 전반적인 변경 사항 수정

src/main/webapp/WEB-INF/views/main.jsp, src/main/webapp/WEB-INF/views/product/product.jsp
=> [BugFix] css

pom.xml
=> [Chore] modify image name

src/main/resources/static/css/order.css, src/main/webapp/WEB-INF/views/order/orderpage.jsp
=> [Bugfix] 멈춰..! 

src/main/webapp/WEB-INF/views/admin/notice-manager.jsp, src/main/webapp/WEB-INF/views/editor/editor-notice-form.jsp
=> 🌟(#148) 관리자 페이지 경로 수정

.github/workflows/main.yml
=> Release 0.0.7

src/main/java/com/saeromteo/app/controller/basket/BasketController.java, src/main/resources/static/css/main.css, src/main/resources/static/css/product.css, src/main/webapp/WEB-INF/views/main.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp, src/main/webapp/WEB-INF/views/product/product.jsp
=> [Feat]: update

src/main/webapp/WEB-INF/views/common/shopnav.jsp
=> 🌟(#163 ) shop nav animation

src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp
=> [Reafactor]: update

src/main/resources/static/css/mypage-collection.css
=> (#212 ) collection.css 수정

src/main/resources/static/css/style.css, src/main/webapp/WEB-INF/views/admin/notice-manager.jsp, src/main/webapp/WEB-INF/views/admin/question-manager.jsp, src/main/webapp/WEB-INF/views/collection/header.jsp, src/main/webapp/WEB-INF/views/faq/faq.jsp, src/main/webapp/WEB-INF/views/notice/notice.jsp, src/main/webapp/WEB-INF/views/question/question-user.jsp, src/main/webapp/WEB-INF/views/question/question-write.jsp, src/main/webapp/WEB-INF/views/question/question.jsp
=> 🌟(#148 ) 디자인 변경, 타이틀 변경

src/main/resources/static/css/main.css
=> 🌟(#148 ) 메인페이지 폰트 사이즈 변경

src/main/webapp/WEB-INF/views/collection/header.jsp
=> 헤더 로그인 버튼 사이즈

src/main/java/com/saeromteo/app/service/collection/CollectionService.java
=> [BugFix] 수거 알림 수정

src/main/java/com/saeromteo/app/service/collection/CollectionService.java, src/main/resources/static/css/basket.css, src/main/webapp/WEB-INF/views/product/product-detail.jsp
=> Release 0.1.1

src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java, src/main/java/com/saeromteo/app/dao/wishlist/WishlistDAO.java, src/main/java/com/saeromteo/app/service/wishlist/WishlistService.java, src/main/resources/mybatis/mappers/wishlistMapper.xml, src/main/resources/static/css/basket.css, src/main/resources/static/css/wishlist.css, src/main/webapp/WEB-INF/views/main.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp, src/main/webapp/WEB-INF/views/product/product-detail.jsp, src/main/webapp/WEB-INF/views/product/product.jsp
=> 🌟(#180)  메인, 위시리스트 수정

src/main/resources/static/css/style.css, src/main/webapp/WEB-INF/views/collection/request-submit.jsp
=> 🌟(#146) 수거 nav바 디자인 수정

src/main/resources/static/css/style.css
=> 🌟(#148 ) 마이페이지 토글 이미지

src/main/resources/static/css/basket.css, src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp
=> [Design]: update basket

src/main/java/com/saeromteo/app/controller/basket/BasketController.java, src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java, src/main/java/com/saeromteo/app/controller/review/ReviewFrontController.java, src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java, src/main/webapp/WEB-INF/views/collection/header.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp, src/main/webapp/WEB-INF/views/review/review.jsp
=> 🌟마이페이지 유저 정보 추가 및 헤더 정보 입력

src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java, src/main/java/com/saeromteo/app/service/collection/CollectionService.java, src/main/java/com/saeromteo/app/util/InspectionUtil.java, src/main/resources/mybatis/mappers/collectionMapper.xml, src/main/webapp/WEB-INF/views/collection/header.jsp, src/main/webapp/WEB-INF/views/common/mypage-nav.jsp, src/main/webapp/WEB-INF/views/main.jsp
=> 수거 알림 수정 및 url 수정

src/main/java/com/saeromteo/app/controller/product/ProductController.java, src/main/webapp/WEB-INF/views/product/product-detail-review.jsp
=> 🌟(#163 ) 리뷰 등록 오류 수정

src/main/resources/static/css/basket.css, src/main/resources/static/css/product-detail-review.css, src/main/webapp/WEB-INF/views/main.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp, src/main/webapp/WEB-INF/views/product/product-detail.jsp, src/main/webapp/WEB-INF/views/product/product.jsp
=> 🌟(#180) 상품 이미지 추가

src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java, src/main/java/com/saeromteo/app/controller/order/OrderController.java, src/main/java/com/saeromteo/app/dao/order/OrderDao.java, src/main/java/com/saeromteo/app/model/order/DeliveryEntity.java, src/main/java/com/saeromteo/app/service/order/OrderService.java, src/main/java/com/saeromteo/app/service/point/PointService.java, src/main/resources/mybatis/OrderSqlMapConfig.xml, src/main/resources/mybatis/mappers/orderMapper.xml, src/main/resources/static/css/order.css, src/main/webapp/WEB-INF/views/mypage/mypage-order-detail.jsp, src/main/webapp/WEB-INF/views/mypage/mypage-order-list.jsp, src/main/webapp/WEB-INF/views/order/afterOrder.jsp, src/main/webapp/WEB-INF/views/order/orderpage.jsp
=> 🌟(#12) 디테일 수정

src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp
=> 🌟(#180) 주문 데이터 전송 수정

src/main/webapp/WEB-INF/views/product/product-detail-review.jsp
=> [Feat]: add product image review

.factorypath, src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java, src/main/java/com/saeromteo/app/service/collection/CollectionService.java
=> 수거 ai 연동정보 변경

src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java, src/main/java/com/saeromteo/app/controller/order/OrderController.java, src/main/resources/mybatis/mappers/orderInquiryMapper.xml, src/main/webapp/WEB-INF/views/mypage/mypage-order-detail.jsp, src/main/webapp/WEB-INF/views/order/orderpage.jsp
=> 🌟(#115) 금액 단위 쉼표 추가

src/main/resources/static/js/auth/reset-email-vaildatecode.js, src/main/webapp/WEB-INF/views/mypage/mypage-profile.jsp
=> 🌟(#212) nickName Length 수정

src/main/resources/static/css/order.css
=> 🌟(#12)  right-section 디자인

src/main/webapp/WEB-INF/views/product/product-detail.jsp, src/main/webapp/WEB-INF/views/product/product-search.jsp, src/main/webapp/WEB-INF/views/product/product.jsp
=> [BugFix]: update

src/main/webapp/WEB-INF/views/product/product-search.jsp
=> [BugFix]: update image

src/main/resources/static/css/question.css
=> 🌟문의사항 문의내용 사진크기 조절

src/main/webapp/WEB-INF/views/mypage/mypage-order-detail.jsp, src/main/webapp/WEB-INF/views/order/orderpage.jsp
=> 배송비 중복 수정 

src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
=> 주문 내역 오류 수정

src/main/java/com/saeromteo/app/controller/order/OrderController.java, src/main/java/com/saeromteo/app/controller/orderInquiry/OrderInquiryController.java, src/main/webapp/WEB-INF/views/order/orderpage.jsp
=> 주문 페이지 수정 

src/main/resources/static/css/envdetail.css, src/main/webapp/WEB-INF/views/admin/envdata-manager.jsp, src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
=> 🌟(#163 ) envdetail 내용 출력 오류 수정

src/main/java/com/saeromteo/app/config/SecurityConfig.java, src/main/webapp/WEB-INF/web.xml
=> [Fix] security

src/main/webapp/WEB-INF/views/mypage/mypage-order-detail.jsp, src/main/webapp/WEB-INF/views/order/orderpage.jsp
=> Zip  Code Ddabong please 

src/main/java/com/saeromteo/app/controller/order/PaymentsController.java, src/main/webapp/WEB-INF/views/mypage/mypage-order-detail.jsp, src/main/webapp/WEB-INF/views/order/orderpage.jsp
=> payment func

src/main/java/com/saeromteo/app/config/SecurityConfig.java
=> [Fix]oauth redirect url

src/main/java/com/saeromteo/app/config/SecurityConfig.java
=>  [Fix] oauth client method

src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java, src/main/java/com/saeromteo/app/controller/order/OrderController.java, src/main/java/com/saeromteo/app/service/order/OrderService.java, src/main/java/com/saeromteo/app/service/orderInquiry/OrderInquiryService.java, src/main/resources/mybatis/mappers/orderInquiryMapper.xml, src/main/webapp/WEB-INF/views/mypage/mypage-order-detail.jsp, src/main/webapp/WEB-INF/views/order/orderpage.jsp
=> order-date desc

src/main/resources/static/js/mypage/mypage-collection.js
=> [BugFix] bugfix

src/main/webapp/WEB-INF/views/order/orderpage.jsp
=> point func
